package com.kh.openapi.model;

import java.io.Serializable;

public class LpWitnessBankNo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_witness_bank_no.bankno
     *
     * @mbggenerated
     */
    private String bankno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_witness_bank_no.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_witness_bank_no.bankclscode
     *
     * @mbggenerated
     */
    private String bankclscode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_witness_bank_no.citycode
     *
     * @mbggenerated
     */
    private String citycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lp_witness_bank_no.bankname
     *
     * @mbggenerated
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table lp_witness_bank_no
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_witness_bank_no.bankno
     *
     * @return the value of lp_witness_bank_no.bankno
     *
     * @mbggenerated
     */
    public String getBankno() {
        return bankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_witness_bank_no.bankno
     *
     * @param bankno the value for lp_witness_bank_no.bankno
     *
     * @mbggenerated
     */
    public void setBankno(String bankno) {
        this.bankno = bankno == null ? null : bankno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_witness_bank_no.status
     *
     * @return the value of lp_witness_bank_no.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_witness_bank_no.status
     *
     * @param status the value for lp_witness_bank_no.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_witness_bank_no.bankclscode
     *
     * @return the value of lp_witness_bank_no.bankclscode
     *
     * @mbggenerated
     */
    public String getBankclscode() {
        return bankclscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_witness_bank_no.bankclscode
     *
     * @param bankclscode the value for lp_witness_bank_no.bankclscode
     *
     * @mbggenerated
     */
    public void setBankclscode(String bankclscode) {
        this.bankclscode = bankclscode == null ? null : bankclscode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_witness_bank_no.citycode
     *
     * @return the value of lp_witness_bank_no.citycode
     *
     * @mbggenerated
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_witness_bank_no.citycode
     *
     * @param citycode the value for lp_witness_bank_no.citycode
     *
     * @mbggenerated
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode == null ? null : citycode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lp_witness_bank_no.bankname
     *
     * @return the value of lp_witness_bank_no.bankname
     *
     * @mbggenerated
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lp_witness_bank_no.bankname
     *
     * @param bankname the value for lp_witness_bank_no.bankname
     *
     * @mbggenerated
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_witness_bank_no
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", bankno=").append(bankno);
        sb.append(", status=").append(status);
        sb.append(", bankclscode=").append(bankclscode);
        sb.append(", citycode=").append(citycode);
        sb.append(", bankname=").append(bankname);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_witness_bank_no
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        LpWitnessBankNo other = (LpWitnessBankNo) that;
        return (this.getBankno() == null ? other.getBankno() == null : this.getBankno().equals(other.getBankno()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getBankclscode() == null ? other.getBankclscode() == null : this.getBankclscode().equals(other.getBankclscode()))
            && (this.getCitycode() == null ? other.getCitycode() == null : this.getCitycode().equals(other.getCitycode()))
            && (this.getBankname() == null ? other.getBankname() == null : this.getBankname().equals(other.getBankname()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_witness_bank_no
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getBankno() == null) ? 0 : getBankno().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getBankclscode() == null) ? 0 : getBankclscode().hashCode());
        result = prime * result + ((getCitycode() == null) ? 0 : getCitycode().hashCode());
        result = prime * result + ((getBankname() == null) ? 0 : getBankname().hashCode());
        return result;
    }
}