package com.kh.openapi.dao;

import com.kh.openapi.model.LpApiList;

public interface LpApiListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_api_list
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_api_list
     *
     * @mbggenerated
     */
    int insert(LpApiList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_api_list
     *
     * @mbggenerated
     */
    int insertSelective(LpApiList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_api_list
     *
     * @mbggenerated
     */
    LpApiList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_api_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LpApiList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_api_list
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LpApiList record);
}