package com.kh.openapi.dao;

import com.kh.openapi.model.LpWitnessBankNo;

public interface LpWitnessBankNoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_witness_bank_no
     *
     * @mbggenerated
     */
    int insert(LpWitnessBankNo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_witness_bank_no
     *
     * @mbggenerated
     */
    int insertSelective(LpWitnessBankNo record);
}