package com.kh.openapi.dao;

import com.kh.openapi.model.LpWitnessBankNoTemp;

public interface LpWitnessBankNoTempMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_witness_bank_no_temp
     *
     * @mbggenerated
     */
    int insert(LpWitnessBankNoTemp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lp_witness_bank_no_temp
     *
     * @mbggenerated
     */
    int insertSelective(LpWitnessBankNoTemp record);
}